### ISSUE TITLE
Update the application to be client side 

### ISSUE THREAD

**Issue by germanattanasio** [boxcarton/say-something-nice#3]
Seems like we are using the Speech SDK but we didn't update the readme and we have Speech to text in the server and the client.

If we update the readme to match the ones we have in github.com/watson-developer-cloud I would love to fork this and host it there

**Comment by joshzzheng** [comment]
We're keeping the script run.py just in case we need to do non-websocket demo.  There will a lot of changes over the next two months for version 2 of the candy machine.  Let's fork it to watson-developer-cloud after this repo is more stable?

**Comment by germanattanasio** [comment]
Ok
